import { User, Item, Request, Message, Notification, Review } from '@/lib/types';

// Mock Users
export const mockUsers: User[] = [
  {
    id: '1',
    email: 'john@example.com',
    name: 'John Doe',
    avatar: 'https://i.pravatar.cc/150?img=1',
    bio: 'Tech enthusiast and outdoor adventurer. Love sharing items with the community!',
    phone: '+1234567890',
    location: {
      city: 'San Francisco',
      state: 'CA',
      country: 'USA',
      coordinates: { lat: 37.7749, lng: -122.4194 },
    },
    verification: {
      email: true,
      phone: true,
      governmentId: 'verified',
      address: true,
    },
    stats: {
      rating: 4.8,
      reviewCount: 24,
      totalBorrowed: 12,
      totalLent: 8,
      activeRentals: 2,
      responseRate: 95,
      responseTime: 'within 2 hours',
      memberSince: new Date('2023-01-15'),
      completionRate: 98,
    },
    preferences: {
      searchRadius: 25,
      defaultPickupWindow: 'Flexible',
      notificationLevel: 'all',
      emailDigest: true,
      pushEnabled: true,
    },
    payoutMethod: {
      type: 'bank',
      last4: '1234',
      verified: true,
    },
    createdAt: new Date('2023-01-15'),
    updatedAt: new Date(),
  },
  {
    id: '2',
    email: 'jane@example.com',
    name: 'Jane Smith',
    avatar: 'https://i.pravatar.cc/150?img=2',
    bio: 'Home improvement enthusiast. Always happy to help!',
    phone: '+1234567891',
    location: {
      city: 'Oakland',
      state: 'CA',
      country: 'USA',
      coordinates: { lat: 37.8044, lng: -122.2712 },
    },
    verification: {
      email: true,
      phone: true,
      governmentId: 'verified',
      address: false,
    },
    stats: {
      rating: 4.9,
      reviewCount: 18,
      totalBorrowed: 5,
      totalLent: 15,
      activeRentals: 3,
      responseRate: 100,
      responseTime: 'within 1 hour',
      memberSince: new Date('2022-11-20'),
      completionRate: 100,
    },
    preferences: {
      searchRadius: 30,
      defaultPickupWindow: 'Mornings only',
      notificationLevel: 'important',
      emailDigest: false,
      pushEnabled: true,
    },
    createdAt: new Date('2022-11-20'),
    updatedAt: new Date(),
  },
];

// Mock Items
export const mockItems: Item[] = [
  {
    id: '1',
    ownerId: '2',
    owner: mockUsers[1],
    title: 'Professional Camera Kit - Canon EOS R5',
    description: 'Complete professional camera setup including Canon EOS R5 body, 24-70mm f/2.8 lens, extra batteries, memory cards, and carrying case. Perfect for events, portraits, or travel photography.',
    category: 'Electronics',
    pricePerDay: 75,
    deposit: 500,
    condition: 'like_new',
    images: [
      'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800',
      'https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=800',
      'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800',
    ],
    primaryImage: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800',
    location: {
      address: '123 Main St',
      city: 'Oakland',
      state: 'CA',
      coordinates: { lat: 37.8044, lng: -122.2712 },
      displayAddress: 'Oakland, CA',
    },
    availability: {
      type: 'calendar',
      blockedDates: [new Date('2024-12-25'), new Date('2024-12-26')],
    },
    pickupInstructions: 'Available for pickup between 9 AM - 6 PM. Please message me to arrange exact time.',
    pickupWindow: 'Flexible',
    tags: ['photography', 'professional', 'camera', 'canon'],
    metadata: {
      views: 245,
      requests: 12,
      bookings: 8,
      rating: 4.9,
      reviewCount: 7,
    },
    status: 'published',
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date(),
    publishedAt: new Date('2024-01-10'),
  },
  {
    id: '2',
    ownerId: '1',
    owner: mockUsers[0],
    title: 'Electric Drill Set with Accessories',
    description: 'Heavy-duty cordless drill with 20+ drill bits and screwdriver attachments. Battery and charger included. Great for home projects!',
    category: 'Tools & Equipment',
    pricePerDay: 15,
    deposit: 100,
    condition: 'good',
    images: [
      'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=800',
      'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800',
    ],
    primaryImage: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=800',
    location: {
      address: '456 Market St',
      city: 'San Francisco',
      state: 'CA',
      coordinates: { lat: 37.7749, lng: -122.4194 },
      displayAddress: 'San Francisco, CA',
    },
    availability: {
      type: 'always',
    },
    pickupInstructions: 'Pickup from my garage. Code will be provided upon confirmation.',
    pickupWindow: 'Flexible',
    tags: ['tools', 'drill', 'home-improvement', 'diy'],
    metadata: {
      views: 189,
      requests: 8,
      bookings: 5,
      rating: 4.7,
      reviewCount: 4,
    },
    status: 'published',
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date(),
    publishedAt: new Date('2024-02-15'),
  },
  {
    id: '3',
    ownerId: '2',
    owner: mockUsers[1],
    title: 'Mountain Bike - Trek X-Caliber 8',
    description: 'Lightweight mountain bike perfect for trails and city riding. Recently serviced, excellent condition. Includes helmet and lock.',
    category: 'Sports & Outdoors',
    pricePerDay: 30,
    deposit: 200,
    condition: 'like_new',
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
      'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=800',
    ],
    primaryImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    location: {
      address: '789 Broadway',
      city: 'Oakland',
      state: 'CA',
      coordinates: { lat: 37.8044, lng: -122.2712 },
      displayAddress: 'Oakland, CA',
    },
    availability: {
      type: 'calendar',
      blockedDates: [],
    },
    pickupInstructions: 'Available weekdays after 5 PM or weekends anytime. Message to coordinate.',
    pickupWindow: 'Evenings & Weekends',
    tags: ['bike', 'cycling', 'outdoor', 'sports'],
    metadata: {
      views: 312,
      requests: 15,
      bookings: 10,
      rating: 4.8,
      reviewCount: 9,
    },
    status: 'published',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date(),
    publishedAt: new Date('2024-03-01'),
  },
];

// Mock Requests
export const mockRequests: Request[] = [
  {
    id: '1',
    itemId: '1',
    item: mockItems[0],
    borrowerId: '1',
    borrower: mockUsers[0],
    ownerId: '2',
    startDate: new Date('2024-12-20'),
    endDate: new Date('2024-12-22'),
    status: 'active',
    pricing: {
      pricePerDay: 75,
      days: 2,
      rentalFee: 150,
      deposit: 500,
      serviceFee: 22.5,
      total: 672.5,
    },
    paymentMethod: {
      type: 'card',
      last4: '4242',
    },
    paymentId: 'pay_123',
    pickupCode: 'ABC123',
    pickupDate: new Date('2024-12-20'),
    createdAt: new Date('2024-12-15'),
    updatedAt: new Date(),
    acceptedAt: new Date('2024-12-16'),
  },
];

// Mock Messages
export const mockMessages: Message[] = [
  {
    id: '1',
    requestId: '1',
    senderId: '1',
    sender: mockUsers[0],
    recipientId: '2',
    text: 'Hi! Is the camera still available for December 20-22?',
    type: 'user',
    read: true,
    createdAt: new Date('2024-12-15T10:00:00'),
    readAt: new Date('2024-12-15T10:05:00'),
  },
  {
    id: '2',
    requestId: '1',
    senderId: '2',
    sender: mockUsers[1],
    recipientId: '1',
    text: 'Yes, it is! I can have it ready for pickup on the 20th.',
    type: 'user',
    read: true,
    createdAt: new Date('2024-12-15T10:10:00'),
    readAt: new Date('2024-12-15T10:12:00'),
  },
];

// Mock Notifications
export const mockNotifications: Notification[] = [
  {
    id: '1',
    userId: '1',
    type: 'request',
    title: 'New Borrow Request',
    message: 'Jane Smith wants to borrow your Camera Kit',
    read: false,
    actionUrl: '/dashboard/my-listings/1',
    actionText: 'View Request',
    relatedId: '1',
    icon: 'BellIcon',
    createdAt: new Date('2024-12-15T09:00:00'),
  },
  {
    id: '2',
    userId: '1',
    type: 'message',
    title: 'New Message',
    message: 'You have a new message from Jane Smith',
    read: false,
    actionUrl: '/dashboard/messages/1',
    actionText: 'Reply',
    relatedId: '1',
    icon: 'ChatBubbleLeftRightIcon',
    createdAt: new Date('2024-12-15T10:00:00'),
  },
];

// Mock Reviews
export const mockReviews: Review[] = [
  {
    id: '1',
    requestId: '1',
    itemId: '1',
    reviewerId: '1',
    reviewer: mockUsers[0],
    revieweeId: '2',
    type: 'item',
    rating: 5,
    comment: 'Excellent camera, exactly as described. Jane was very responsive and helpful!',
    wouldRecommend: true,
    createdAt: new Date('2024-12-23'),
  },
];



